name: Test and lint

on: [pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Cache Node.js tests paths
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint
